/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Skylar Muffin (https://sketchfab.com/boopdesignstudio)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/stylized-3d-floating-island-and-mine-house-3cb24182a8504d439ee4e3c500565ac5
Title: Stylized 3D Floating Island And Mine House
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export default function Island({isRotating, setIsRotating, setCurrentStage, scale, ...props}: {isRotating: boolean, setIsRotating: (isRotating: boolean) => void, setCurrentStage: (stage: number) => void, scale?: [number, number, number] | null} & any) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const { gl, viewport } = useThree()
  const islandRef = useRef<THREE.Group>(null)
  // Calculates delta x for rotation 
  const lastX = useRef(0)
  const rotationSpeed = useRef(0)
  const keyPressed = useRef<string | null>(null)
  const dampingFactor = 0.95
  const keyRotationSpeed = 0.015
  const pointerSpeed = 0.001


  useFrame(() => {
    // Apply damping 
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor 
      islandRef.current.rotation.y += rotationSpeed.current
    } else {
      // Rotate based on key press
      if (keyPressed.current === "ArrowLeft") {
        islandRef.current.rotation.y += keyRotationSpeed 
      } else if (keyPressed.current === "ArrowRight") {
        islandRef.current.rotation.y -= keyRotationSpeed 
      }
    }

  })
  // Holding down to rotate -> set isRotating to true
  const handlePointerDown = (e: React.PointerEvent) => {
    e.stopPropagation()
    e.preventDefault()
    setIsRotating(true)
    const clientX = e.touches 
    ? e.touches[0].clientX 
    : e.clientX 

    lastX.current = clientX     
    const delta = (clientX - lastX.current)/ viewport.width
    lastX.current = clientX 
    rotationSpeed.current = delta * pointerSpeed * Math.PI
  }

  const handlePointerUp = (e: React.PointerEvent) => {
    e.stopPropagation()
    e.preventDefault()
    setIsRotating(false)
  }

  const handlePointerMove = (e: React.PointerEvent) => {
    e.stopPropagation()
    e.preventDefault()

    if (!isRotating) return
    const clientX = e.touches 
    ? e.touches[0].clientX 
    : e.clientX 

    const delta = (clientX - lastX.current)/ viewport.width
    islandRef.current.rotation.y += delta * pointerSpeed * Math.PI 
    lastX.current = clientX 
    rotationSpeed.current = delta * pointerSpeed * Math.PI  
  }

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      keyPressed.current = e.key
      setIsRotating(true)
    }
  }

  const handleKeyUp = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      keyPressed.current = null
      setIsRotating(false) 
    }
  }

  useEffect(() => {
    const canvas = gl.domElement
    canvas.addEventListener('pointerdown', handlePointerDown)
    canvas.addEventListener('pointerup', handlePointerUp)
    canvas.addEventListener('pointermove', handlePointerMove)
    document.addEventListener("keydown", handleKeyDown)
    document.addEventListener("keyup", handleKeyUp)
    
    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown)
      canvas.removeEventListener('pointerup', handlePointerUp)
      canvas.removeEventListener('pointermove', handlePointerMove)
      document.removeEventListener("keydown", handleKeyDown)
      document.removeEventListener("keyup", handleKeyUp)
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  return (
    <group ref = {islandRef} {...props} position = {[0,0,-4.25]} rotation = {[0.1,-0.05,0]} scale = {scale || [1,1,1]}>
    <group dispose={null}>
      <group scale={0.05}>
        <group position = {[-30, 0, -20]} rotation = {[0,4.5,-0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Bridge_Mat001_0.geometry}
            material={materials['SF_Bridge_Mat.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Roof_Final_0.geometry}
            material={materials.SF_Roof_Final}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Roof_Final_0_1.geometry}
            material={materials.SF_Roof_Final}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Roof_Final_0_2.geometry}
            material={materials.SF_Roof_Final}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Roof_Final_0_3.geometry}
            material={materials.SF_Roof_Final}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Rocks_Mat_0.geometry}
            material={materials.SF_Rocks_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Windows_Mat_0.geometry}
            material={materials.SF_Windows_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Windows_Mat_0_1.geometry}
            material={materials.SF_Windows_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Windows_Mat_0_2.geometry}
            material={materials.SF_Windows_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Bush_Mat_0.geometry}
            material={materials.SF_Bush_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_TreeWood_Mat_0.geometry}
            material={materials.SF_TreeWood_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_TreeWood_Mat_0_1.geometry}
            material={materials.SF_TreeWood_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_TreeLeaf_Mat_0.geometry}
            material={materials.SF_TreeLeaf_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_HouseSupport_Mat_0.geometry}
            material={materials.SF_HouseSupport_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_HouseJoins_Mat_0.geometry}
            material={materials.SF_HouseJoins_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Chimney_Mat_0.geometry}
            material={materials.SF_Chimney_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_CutRock_Mat_0.geometry}
            material={materials.SF_CutRock_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Stalagmites_Mat_0.geometry}
            material={materials.SF_Stalagmites_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_WoodTex_Mat_0.geometry}
            material={materials.SF_WoodTex_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_PlasterTex_Mat_0.geometry}
            material={materials.SF_PlasterTex_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_StoneBrick_Mat_0.geometry}
            material={materials.SF_StoneBrick_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Island_Mat_0.geometry}
            material={materials.SF_Island_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_LampGlass_Mat_0.geometry}
            material={materials.SF_LampGlass_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Lamp_Mat_0.geometry}
            material={materials.SF_Lamp_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Candle_Mat_0.geometry}
            material={materials.SF_Candle_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Grass_Mat_0.geometry}
            material={materials.SF_Grass_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Rail_Mat_0.geometry}
            material={materials.SF_Rail_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_GrassCards_Mat_0.geometry}
            material={materials.SF_GrassCards_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_GrassCards_Mat_0_1.geometry}
            material={materials.SF_GrassCards_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_GrassCards_Mat_0_2.geometry}
            material={materials.SF_GrassCards_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_GrassCards_Mat_0_3.geometry}
            material={materials.SF_GrassCards_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Sack_Mat_0.geometry}
            material={materials.SF_Sack_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_MineCart_Mat_0.geometry}
            material={materials.SF_MineCart_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Bridge_Mat_0.geometry}
            material={materials.SF_Bridge_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Door_Mat_0.geometry}
            material={materials.SF_Door_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Water_Mat_0.geometry}
            material={materials.SF_Water_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_Final_Water001_0.geometry}
            material={materials['Final_Water.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_Final_Rocks2_Mat_0.geometry}
            material={materials.Final_Rocks2_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_ButterFly_Mat_0.geometry}
            material={materials.SF_ButterFly_Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Final_Bridge1_SF_Lillypad_Mat_0.geometry}
            material={materials.SF_Lillypad_Mat}
          />
        </group>
      </group>
    </group>
    </group>
  )
}