/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/
import { useRef } from 'react'
import { useTexture } from '@react-three/drei'
import { Sphere } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Sky({ isRotating, ...props }: {isRotating: boolean, [key: string]: any}) {
  const texture = useTexture('/skyTextures/Scene_-_Root_diffuse.jpeg')
  const skyRef = useRef<THREE.Mesh|null>(null)

  useFrame((_, delta) => {
    if (isRotating && skyRef.current) {
      skyRef.current.rotation.y += 0.25 * delta
    } else {
      if (skyRef.current && skyRef.current.rotation.y > 0.05) {
        skyRef.current.rotation.y -= 0.001
      } else {
        skyRef.current.rotation.y = 0
      }
    }
  })

  return (
    <Sphere {...props} args={[100, 64, 64]} ref = {skyRef} rotation = {[Math.PI, 0, 0]}>
      <meshBasicMaterial map={texture} side={THREE.BackSide} />
    </Sphere>
  )
}